from jenkins/jenkins:lts

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# install Maven
USER root
RUN apt-get update && apt-get install -y maven
USER jenkins
